/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Jun 13 09:36:47 GMT 2022
 */

package net.finmath.marketdata.model.curves;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class DiscountCurveFromForwardCurve_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "net.finmath.marketdata.model.curves.DiscountCurveFromForwardCurve"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\HARDIK~1\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "IN"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Hardik Rana\\Intellij_projects\\finmath-lib"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Hardik Rana"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Hardik Rana"); 
    java.lang.System.setProperty("user.timezone", "Asia/Calcutta"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(DiscountCurveFromForwardCurve_ESTest_scaffolding.class.getClassLoader() ,
      "net.finmath.marketdata.model.curves.DiscountCurveRenormalized",
      "net.finmath.time.TimeDiscretizationFromArray$3",
      "org.apache.commons.math3.linear.RealVectorFormat",
      "net.finmath.time.TimeDiscretizationFromArray$2",
      "net.finmath.integration.PiecewiseContantDoubleUnaryOperator",
      "net.finmath.time.TimeDiscretizationFromArray$1",
      "org.apache.commons.math3.linear.FieldVector",
      "net.finmath.marketdata.model.curves.DiscountCurveFromForwardCurve",
      "net.finmath.time.daycount.DayCountConvention_ACT",
      "org.apache.commons.math3.linear.RealVector",
      "org.apache.commons.math3.exception.MathArithmeticException",
      "net.finmath.optimizer.LevenbergMarquardt$2",
      "org.apache.commons.math3.util.FastMath$lnMant",
      "net.finmath.marketdata.model.curves.CurveInterpolation$Point",
      "net.finmath.marketdata.model.curves.CurveBuilder",
      "net.finmath.time.daycount.DayCountConvention_ACT_ACT_YEARFRAC",
      "org.apache.commons.math3.linear.FieldMatrix",
      "net.finmath.marketdata.model.curves.ForwardCurve",
      "org.apache.commons.math3.RealFieldElement",
      "net.finmath.marketdata.model.curves.ForwardCurveNelsonSiegelSvensson",
      "net.finmath.optimizer.LevenbergMarquardt$1",
      "org.apache.commons.math3.exception.MathIllegalArgumentException",
      "net.finmath.marketdata.calibration.ParameterObject",
      "net.finmath.marketdata.model.curves.CurveInterpolation$InterpolationEntity",
      "org.apache.commons.math3.exception.ZeroException",
      "org.apache.commons.math3.linear.Array2DRowFieldMatrix",
      "org.apache.commons.math3.util.FastMath",
      "net.finmath.marketdata.model.volatilities.CapletVolatilitiesParametricFourParameterPicewiseConstant",
      "org.apache.commons.math3.FieldElement",
      "net.finmath.time.TimeDiscretizationFromArray",
      "org.apache.commons.math3.random.RandomVectorGenerator",
      "net.finmath.optimizer.Optimizer$ObjectiveFunction",
      "net.finmath.optimizer.OptimizerFactoryLevenbergMarquardt$1",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingTARGETHolidays",
      "net.finmath.marketdata.model.curves.CurveInterpolation$InterpolationMethod",
      "org.apache.commons.math3.random.MersenneTwister",
      "net.finmath.marketdata.calibration.Solver",
      "org.apache.commons.math3.linear.RealMatrix",
      "org.apache.commons.math3.exception.NotFiniteNumberException",
      "net.finmath.randomnumbers.SobolSequence",
      "net.finmath.optimizer.LevenbergMarquardt",
      "org.apache.commons.math3.exception.util.ExceptionContextProvider",
      "org.apache.commons.math3.linear.BlockRealMatrix",
      "net.finmath.time.daycount.DayCountConvention_ACT_ACT_ICMA",
      "org.apache.commons.math3.util.FastMath$Split",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarAny",
      "org.apache.commons.math3.linear.BlockFieldMatrix",
      "net.finmath.time.daycount.DayCountConvention_ACT_ACT_ISDA",
      "net.finmath.marketdata.model.curves.DiscountCurveInterpolation",
      "net.finmath.optimizer.OptimizerFactoryLevenbergMarquardt",
      "org.apache.commons.math3.exception.NumberIsTooSmallException",
      "org.apache.commons.math3.util.FastMath$ExpIntTable",
      "net.finmath.marketdata.model.AnalyticModel",
      "org.apache.commons.math3.exception.MathIllegalStateException",
      "net.finmath.marketdata.model.curves.AbstractForwardCurve",
      "org.apache.commons.math3.linear.NonSquareMatrixException",
      "org.apache.commons.math3.util.FastMath$ExpFracTable",
      "org.apache.commons.math3.linear.MatrixUtils",
      "net.finmath.time.TimeDiscretization",
      "net.finmath.time.TenorFromArray",
      "org.apache.commons.math3.linear.NonSymmetricMatrixException",
      "net.finmath.interpolation.BiLinearInterpolation",
      "net.finmath.marketdata.calibration.ParameterTransformation",
      "org.apache.commons.math3.linear.Array2DRowRealMatrix",
      "org.apache.commons.math3.util.FastMath$CodyWaite",
      "org.apache.commons.math3.util.MathUtils",
      "net.finmath.marketdata.model.curves.SeasonalCurve$Builder",
      "org.apache.commons.math3.util.CompositeFormat",
      "net.finmath.time.daycount.DayCountConvention_30E_360",
      "org.apache.commons.math3.linear.AbstractRealMatrix",
      "net.finmath.marketdata.model.curves.PiecewiseCurve",
      "org.apache.commons.math3.exception.MathParseException",
      "net.finmath.marketdata.model.curves.SeasonalCurve",
      "org.apache.commons.math3.exception.DimensionMismatchException",
      "net.finmath.interpolation.RationalFunctionInterpolation$1",
      "net.finmath.marketdata.model.volatilities.VolatilitySurface",
      "net.finmath.time.daycount.DayCountConvention_ACT_365L",
      "net.finmath.marketdata.model.curves.DiscountCurveFromProductOfCurves",
      "net.finmath.marketdata.model.volatilities.AbstractVolatilitySurfaceParametric",
      "org.apache.commons.lang3.Validate",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendar$DateOffsetUnit",
      "org.apache.commons.math3.exception.util.ExceptionContext",
      "org.apache.commons.math3.linear.RealVectorPreservingVisitor",
      "org.apache.commons.math3.linear.RealVectorChangingVisitor",
      "net.finmath.marketdata.model.curves.ForwardCurveInterpolation$1",
      "net.finmath.marketdata.model.curves.CurveInterpolation",
      "net.finmath.exception.CalculationException",
      "net.finmath.marketdata.model.curves.PiecewiseCurve$Builder",
      "net.finmath.time.daycount.DayCountConvention_ACT_365A",
      "net.finmath.time.FloatingpointDate",
      "net.finmath.marketdata.model.curves.ForwardCurveFromDiscountCurve",
      "org.apache.commons.math3.linear.RealVector$2",
      "net.finmath.time.daycount.DayCountConvention_UNKNOWN",
      "net.finmath.randomnumbers.VanDerCorputSequence",
      "net.finmath.optimizer.SolverException",
      "net.finmath.functions.LinearAlgebra",
      "net.finmath.randomnumbers.SobolSequence1D",
      "net.finmath.interpolation.RationalFunctionInterpolation",
      "net.finmath.time.daycount.DayCountConvention_30E_360_ISDA",
      "net.finmath.time.daycount.DayCountConvention_ACT_365",
      "net.finmath.marketdata.model.curves.DiscountCurve",
      "net.finmath.time.daycount.DayCountConvention_NL_365",
      "net.finmath.marketdata.model.curves.CurveFromProductOfCurves",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingLONHolidays",
      "net.finmath.marketdata.model.curves.Curve",
      "net.finmath.time.daycount.DayCountConvention_ACT_360",
      "net.finmath.marketdata.model.curves.ForwardCurveNelsonSiegelSvensson$1",
      "net.finmath.marketdata.model.curves.AbstractCurve",
      "org.apache.commons.math3.exception.OutOfRangeException",
      "org.apache.commons.math3.exception.NotPositiveException",
      "org.apache.commons.math3.exception.MathInternalError",
      "net.finmath.optimizer.OptimizerFactory",
      "net.finmath.time.daycount.DayCountConvention_30U_360",
      "net.finmath.randomnumbers.RandomNumberGenerator",
      "org.apache.commons.math3.linear.ArrayRealVector",
      "net.finmath.time.daycount.DayCountConvention",
      "org.apache.commons.math3.exception.MathUnsupportedOperationException",
      "net.finmath.marketdata.model.AnalyticModelFromCurvesAndVols",
      "org.apache.commons.math3.linear.RealMatrixFormat",
      "net.finmath.marketdata.model.volatilities.CapletVolatilitiesParametricDisplacedFourParameterAnalytic",
      "org.apache.commons.math3.linear.LUDecomposition$1",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingNYCHolidays",
      "org.apache.commons.math3.linear.AbstractFieldMatrix",
      "org.apache.commons.math3.linear.SparseRealMatrix",
      "net.finmath.interpolation.RationalFunctionInterpolation$RationalFunction",
      "net.finmath.marketdata.model.curves.IndexCurveFromDiscountCurve",
      "org.apache.commons.math3.exception.NumberIsTooLargeException",
      "net.finmath.time.TimeDiscretizationFromArray$ShortPeriodLocation",
      "org.apache.commons.math3.analysis.BivariateFunction",
      "org.apache.commons.math3.exception.NotStrictlyPositiveException",
      "org.apache.commons.math3.linear.FieldMatrixChangingVisitor",
      "net.finmath.marketdata.model.volatilities.VolatilitySurface$QuotingConvention",
      "net.finmath.marketdata.model.volatilities.AbstractVolatilitySurface",
      "org.apache.commons.math3.exception.NoDataException",
      "org.apache.commons.math3.analysis.UnivariateFunction",
      "org.apache.commons.math3.linear.RealLinearOperator",
      "net.finmath.marketdata.model.curves.ForwardCurveInterpolation$InterpolationEntityForward",
      "net.finmath.marketdata.model.curves.DiscountCurveNelsonSiegelSvensson",
      "net.finmath.time.businessdaycalendar.AbstractBusinessdayCalendar",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingWeekends",
      "org.apache.commons.math3.linear.RealMatrixPreservingVisitor",
      "net.finmath.time.Tenor",
      "org.apache.commons.math3.linear.OpenMapRealMatrix",
      "org.apache.commons.lang3.ArrayUtils",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendar",
      "net.finmath.marketdata.calibration.Solver$1",
      "org.apache.commons.math3.linear.SingularMatrixException",
      "net.finmath.marketdata.model.curves.CurveInterpolation$Builder",
      "org.apache.commons.math3.random.SobolSequenceGenerator",
      "org.apache.commons.math3.linear.MatrixDimensionMismatchException",
      "org.apache.commons.math3.linear.FieldMatrixPreservingVisitor",
      "net.finmath.optimizer.Optimizer",
      "org.apache.commons.math3.random.BitsStreamGenerator",
      "org.apache.commons.math3.linear.DecompositionSolver",
      "net.finmath.modelling.Model",
      "org.apache.commons.math3.linear.LUDecomposition$Solver",
      "net.finmath.marketdata.model.curves.CurveInterpolation$ExtrapolationMethod",
      "net.finmath.time.daycount.DayCountConvention_NONE",
      "org.apache.commons.math3.exception.MultiDimensionMismatchException",
      "net.finmath.randomnumbers.RandomNumberGenerator1D",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendar$DateRollConvention",
      "net.finmath.optimizer.OptimizerFactoryCMAES",
      "net.finmath.time.daycount.DayCountConvention_ACT_ACT_AFB",
      "org.apache.commons.math3.exception.MathIllegalNumberException",
      "net.finmath.randomnumbers.MersenneTwister",
      "org.apache.commons.math3.linear.AnyMatrix",
      "net.finmath.marketdata.calibration.ParameterAggregation",
      "net.finmath.interpolation.RationalFunctionInterpolation$ExtrapolationMethod",
      "net.finmath.marketdata.model.curves.CurveInterpolation$1",
      "org.apache.commons.math3.exception.util.Localizable",
      "net.finmath.marketdata.model.volatilities.CapletVolatilities",
      "net.finmath.marketdata.model.curves.ForwardCurveInterpolation",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingGivenHolidays",
      "org.apache.commons.math3.linear.LUDecomposition",
      "org.apache.commons.math3.random.RandomGenerator",
      "org.apache.commons.math3.exception.NullArgumentException",
      "net.finmath.interpolation.RationalFunctionInterpolation$InterpolationMethod",
      "org.apache.commons.math3.Field",
      "org.apache.commons.math3.linear.RealMatrixChangingVisitor",
      "org.apache.commons.math3.util.FastMathLiteralArrays",
      "net.finmath.marketdata.model.curves.ForwardCurveWithFixings",
      "net.finmath.marketdata.model.volatilities.CapletVolatilitiesParametric"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(DiscountCurveFromForwardCurve_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "net.finmath.marketdata.model.curves.AbstractCurve",
      "net.finmath.marketdata.model.curves.DiscountCurveFromForwardCurve",
      "net.finmath.time.businessdaycalendar.AbstractBusinessdayCalendar",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingTARGETHolidays",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingWeekends",
      "net.finmath.marketdata.model.AnalyticModelFromCurvesAndVols",
      "net.finmath.marketdata.model.curves.CurveInterpolation",
      "net.finmath.marketdata.model.curves.AbstractForwardCurve",
      "net.finmath.marketdata.model.curves.ForwardCurveInterpolation",
      "net.finmath.marketdata.model.curves.CurveInterpolation$1",
      "net.finmath.marketdata.model.curves.CurveInterpolation$Point",
      "net.finmath.marketdata.model.curves.ForwardCurveInterpolation$1",
      "net.finmath.time.daycount.DayCountConvention_ACT",
      "net.finmath.time.daycount.DayCountConvention_ACT_365",
      "net.finmath.time.FloatingpointDate",
      "net.finmath.marketdata.model.curves.DiscountCurveFromProductOfCurves",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendar$DateOffsetUnit",
      "org.apache.commons.lang3.Validate",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingGivenHolidays",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingLONHolidays",
      "net.finmath.time.daycount.DayCountConvention_UNKNOWN",
      "net.finmath.marketdata.model.curves.ForwardCurveNelsonSiegelSvensson",
      "net.finmath.marketdata.model.curves.DiscountCurveNelsonSiegelSvensson",
      "net.finmath.marketdata.model.curves.DiscountCurveInterpolation",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarAny",
      "net.finmath.interpolation.RationalFunctionInterpolation",
      "net.finmath.interpolation.RationalFunctionInterpolation$InterpolationMethod",
      "net.finmath.interpolation.RationalFunctionInterpolation$ExtrapolationMethod",
      "net.finmath.interpolation.RationalFunctionInterpolation$1",
      "net.finmath.interpolation.RationalFunctionInterpolation$RationalFunction",
      "net.finmath.time.businessdaycalendar.BusinessdayCalendarExcludingNYCHolidays",
      "net.finmath.marketdata.model.curves.ForwardCurveFromDiscountCurve",
      "net.finmath.time.daycount.DayCountConvention_ACT_365L",
      "net.finmath.marketdata.model.curves.PiecewiseCurve",
      "net.finmath.marketdata.model.curves.ForwardCurveWithFixings",
      "net.finmath.marketdata.model.volatilities.AbstractVolatilitySurface",
      "net.finmath.marketdata.model.volatilities.AbstractVolatilitySurfaceParametric",
      "net.finmath.marketdata.model.volatilities.CapletVolatilitiesParametric",
      "net.finmath.time.daycount.DayCountConvention_NONE",
      "net.finmath.time.daycount.DayCountConvention_ACT_ACT_ICMA",
      "net.finmath.time.daycount.DayCountConvention_30E_360_ISDA",
      "net.finmath.marketdata.model.curves.CurveInterpolation$Builder",
      "net.finmath.marketdata.model.volatilities.CapletVolatilitiesParametricDisplacedFourParameterAnalytic",
      "net.finmath.time.daycount.DayCountConvention_ACT_ACT_YEARFRAC",
      "net.finmath.time.daycount.DayCountConvention_ACT_ACT_ISDA",
      "net.finmath.marketdata.calibration.Solver",
      "net.finmath.marketdata.calibration.ParameterAggregation",
      "net.finmath.time.daycount.DayCountConvention_ACT_ACT_AFB",
      "net.finmath.time.daycount.DayCountConvention_NL_365",
      "net.finmath.time.TimeDiscretizationFromArray",
      "net.finmath.time.TimeDiscretizationFromArray$3",
      "net.finmath.marketdata.model.volatilities.CapletVolatilitiesParametricFourParameterPicewiseConstant",
      "net.finmath.marketdata.model.curves.CurveFromProductOfCurves",
      "net.finmath.time.daycount.DayCountConvention_30E_360",
      "net.finmath.optimizer.OptimizerFactoryLevenbergMarquardt",
      "net.finmath.time.daycount.DayCountConvention_ACT_360",
      "net.finmath.marketdata.model.curves.SeasonalCurve",
      "net.finmath.time.daycount.DayCountConvention_30U_360",
      "net.finmath.time.TenorFromArray",
      "net.finmath.marketdata.calibration.Solver$1",
      "net.finmath.optimizer.LevenbergMarquardt",
      "net.finmath.optimizer.OptimizerFactoryLevenbergMarquardt$1",
      "net.finmath.optimizer.LevenbergMarquardt$2",
      "net.finmath.functions.LinearAlgebra",
      "org.apache.commons.math3.linear.LUDecomposition",
      "org.apache.commons.math3.linear.RealLinearOperator",
      "org.apache.commons.math3.linear.RealMatrixFormat",
      "org.apache.commons.math3.util.CompositeFormat",
      "org.apache.commons.math3.linear.AbstractRealMatrix",
      "org.apache.commons.math3.linear.Array2DRowRealMatrix",
      "org.apache.commons.math3.util.MathUtils",
      "org.apache.commons.math3.util.FastMath",
      "org.apache.commons.math3.linear.LUDecomposition$Solver",
      "org.apache.commons.math3.linear.MatrixUtils",
      "net.finmath.time.daycount.DayCountConvention_ACT_365A",
      "net.finmath.marketdata.model.curves.DiscountCurveRenormalized",
      "net.finmath.optimizer.OptimizerFactoryCMAES",
      "net.finmath.marketdata.model.volatilities.CapletVolatilities",
      "net.finmath.time.TimeDiscretizationFromArray$1",
      "net.finmath.marketdata.model.curves.ForwardCurveNelsonSiegelSvensson$1",
      "net.finmath.time.TimeDiscretizationFromArray$2",
      "net.finmath.randomnumbers.VanDerCorputSequence",
      "net.finmath.marketdata.model.curves.IndexCurveFromDiscountCurve",
      "net.finmath.randomnumbers.MersenneTwister",
      "org.apache.commons.math3.random.BitsStreamGenerator",
      "org.apache.commons.math3.random.MersenneTwister",
      "net.finmath.integration.PiecewiseContantDoubleUnaryOperator",
      "org.apache.commons.lang3.ArrayUtils",
      "net.finmath.interpolation.BiLinearInterpolation",
      "net.finmath.randomnumbers.SobolSequence1D",
      "net.finmath.randomnumbers.SobolSequence",
      "org.apache.commons.math3.util.FastMath$Split",
      "org.apache.commons.math3.random.SobolSequenceGenerator"
    );
  }
}
